### ISSUE TITLE
TextInput causing frustration

### ISSUE THREAD

**Issue by ghost** [inclement/kivycrashcourse#1]
Hi, I have a question. Everytime I use the TextInput widget and I try to get the input value from it, I do not get the typed string... What am I doing wrong? I'm writing this from my phone and I have the code on my PC, Ill send it to you if you can do somethibg with it. I find Kivy and the self.something_something most confusing. I've tried using the TextInput widget in many ways in different apps but TextInput NEVER gives me a string. What's going on? This is causing frustration of the utmost degree and I saw your video on buildozer and this is my very last hope!

**Comment by inclement** [comment]
I suggest asking on the kivy irc channelr or kivy-users mailing list, and including some example code demonstrating the problem.
